### ISSUE TITLE
Python3 Error

### ISSUE THREAD

**Issue by jtdub** [netopsio/netlib#17]
```
Traceback (most recent call last):
  File "./nl3.py", line 7, in <module>
    s.connect()
  File "/usr/local/lib/python3.5/site-packages/netlib-0.0.7-py3.5.egg/netlib/conn_type.py", line 26, in connect
  File "/usr/local/lib/python3.5/site-packages/paramiko/channel.py", line 613, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.5/site-packages/paramiko/buffered_pipe.py", line 163, in read
    if len(self._buffer) <= nbytes:
TypeError: unorderable types: int() <= str()
```

**Comment by jtdub** [comment]
Fixed in https://github.com/netopsio/netlib/pull/18
